In [78]:
p=[]
a=list()
b=list()
a=["CL69202",18]
b=["CL63204",15]
a+b


['CL69202', 18, 'CL63204', 15]

In [18]:
a=[1, 4, 5, 6]
b=[2, 2, 2, 2]

a+b

[1, 4, 5, 6, 2, 2, 2, 2]

In [28]:
a=[1, 4, 5, 6]
b=[2, 2, 2, 2]

for i in range(0,4):
    print(a[i]+b[i])


3
6
7
8


In [32]:
import array as built_in
array1 = built_in.array('i', [1, 2]) # format is array1 = built_in.array(typecode, initializer), the initializer can be 0
array1.append(3)
array1.append(4)
print(array1)

array('i', [1, 2, 3, 4])


In [36]:
import array as built_in
array1 = built_in.array('f', [1.5, 2.5]) # f is for float type 
array1.append(3.5)
array1.append(4.5)
print(array1)

array('f', [1.5, 2.5, 3.5, 4.5])


In [38]:
import numpy as np

a=np.array([1, 4, 5, 6])
b=np.array([2, 2, 2, 2])

a+b

array([3, 6, 7, 8])

In [39]:
import numpy as np

a=np.array([1, 4, 5.0, 6])
b=np.array([2, 2, 2, 2])

a+b

array([3., 6., 7., 8.])

In [47]:
import numpy as np

a=np.zeros((4)) #one dimensional

print(a)

print(np.shape(a))

[0. 0. 0. 0.]
(4,)


In [48]:
import numpy as np

a=np.zeros((1,2)) #two dimensional

print(a)

print(np.shape(a)) #Number of rows and columns

[[0. 0.]]
(1, 2)


In [49]:
import numpy as np

a=np.zeros((4,5)) #two dimensional

print(a)

print(np.shape(a))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(4, 5)


In [51]:
import numpy as np

a=np.zeros((4,5,6)) #3 dimensional

print(a)

print(np.shape(a))

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
(4, 5, 6)


In [62]:
import numpy as np

a=np.zeros((2,2))
a[0,0]=1
a[0,1]=2
a[1,0]=3
a[1,1]=4

print(np.mean(a))


2.5


In [63]:
import numpy as np

a=np.zeros((2,2))
a[0,0]=1
a[0,1]=2
a[1,0]=3
a[1,1]=4

print(np.mean(a[:,0]))

2.0


In [65]:
import numpy as np

a=np.zeros((2,2))
a[0,0]=1
a[0,1]=2
a[1,0]=3
a[1,1]=4

print(np.mean(a[:,1]))

3.0


In [83]:
from urllib import request
# Define the remote file to retrieve
remote_url = 'https://www.dropbox.com/s/34pbn6cm1c8w2zg/temp_anomaly_global.txt?dl=0'
# Define the local filename to save data
local_file = 'local_temp.txt'
# Download remote and save locally
request.urlretrieve(remote_url, local_file)

('local_temp.txt', <http.client.HTTPMessage at 0x7ff752f57af0>)

In [68]:
import numpy as np 
import pandas as pd 
import os 
import sys
import matplotlib
import matplotlib.pyplot as plt
f2=[]
f2 = np.loadtxt('../../data_files/temp_anomaly_global.txt') 
print(np.shape(f2))
#plt.plot(f2[:,0],f2[:,2],f2[:,0],f2[:,6],f2[:,0],f2[:,4],f2[:,0],f2[:,9])
#plt.show()

(172, 12)


In [75]:
import numpy as np 

f2=[]
f2 = np.loadtxt('../../data_files/temp_anomaly_global.txt') 
print(np.shape(f2))
a=np.shape(f2)
print(a[0],a[1])

(172, 12)
172 12
